### ISSUE TITLE
(1) 뉴스레터

### ISSUE THREAD

**Issue by hayneseo** [hayneseo/2020-6#10]
기획안
https://www.notion.so/postype/2020-6-1-ver-5756b4d9a75448abb18e75a86e8394b6

- [ ] #5 포타레터 디자인 요소 확정
- [ ] #6 1호 원고 작성
- [ ] #7 html/코드 스터디
- [ ] #8 1호 발행 일정 확정
